export const GET_BILLS_STARTED = "GET_BILLS_STARTED";
export const GET_BILLS = "GET_BILLS";
export const GET_BILLS_ENDED = "GET_BILLS_ENDED";
export const GET_BILLS_ERROR = "GET_BILLS_ERROR";

export const FILTER_BILLS_TYPE_STARTED = "FILTER_BILLS_TYPE_STARTED";
export const FILTER_BILLS_TYPE = "FILTER_BILLS_TYPE";
export const FILTER_BILLS_TYPE_ENDED = "FILTER_BILLS_TYPE_ENDED";

export const FILTER_BILLS_FAVORITES = "FILTER_BILLS_FAVORITES";
export const UNFILTER_BILLS_FAVORITES = "UNFILTER_BILLS_FAVORITES";

export const ADD_BILL_TO_FAVORITES = "ADD_BILL_TO_FAVORITES";
export const REMOVE_BILL_FROM_FAVORITES = "REMOVE_BILL_FROM_FAVORITES";

export const CHANGE_LOCALE = "CHANGE_LOCALE";
